#define CPPATH ""
#define CPVersion "0.1"

#include "configs\dialogs\cp_dialogs.hpp"
#include "configs\dialogs\gearPanel\respawnPanel.hpp"
#include "configs\dialogs\gearPanel\squadsPanel.hpp"
#include "configs\dialogs\gearPanel\gearPanel.hpp"
#include "configs\dialogs\gearPanel\weaponsPanel.hpp"
#include "configs\dialogs\gearPanel\accessoriesPanel.hpp"
#include "configs\dialogs\gearPanel\uniformPanel.hpp"
