#include "dialogs\compassDialog.hpp"
#include "dialogs\uavDialog.hpp"
#include "dialogs\mccRscHitDown.hpp"
#include "dialogs\mccRscHitLeft.hpp"
#include "dialogs\mccRscHitRight.hpp"
#include "dialogs\mccRscHitUp.hpp"